apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: authservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authservice
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: authservice
          image: {{ .Values.global.registry }}{{ .Values.global.authservice.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "750Mi"
              cpu: 250m
          {{- include "authservice.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.authservice.port | default .Values.authservice.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: authservice
          ports:
          - containerPort: {{ .Values.global.authservice.port | default .Values.authservice.port }}
