apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - authservice.{{ .Values.global.domain }}
  - authservice.sfdcdemo.svc.cluster.local
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: authservice
        subset: v2