apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.global.registry }}{{ .Values.global.rabbitmq.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "750Mi"
              cpu: 500m
          {{- include "rabbitmq.healthProbes" . | indent 10 }}
          ports:
          - containerPort: 4369
          - containerPort: 5671
          - containerPort: {{ .Values.global.rabbitmq.server.port | default .Values.rabbitmq.server.port }}
          - containerPort: 15671
          - containerPort: {{ .Values.global.rabbitmq.management.port | default .Values.rabbitmq.management.port }}
          - containerPort: 25672
