apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rabbitmq
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - rabbitmq.{{ .Values.global.domain }}
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: rabbitmq
        port:
          number: {{ .Values.global.rabbitmq.management.port | default .Values.rabbitmq.management.port }}