apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-rmqmanagement"
    port: {{ .Values.global.rabbitmq.management.port | default .Values.rabbitmq.management.port }}
    targetPort: {{ .Values.global.rabbitmq.management.port | default .Values.rabbitmq.management.port }}
  - name: "tcp-rabbitmq"
    port: {{ .Values.global.rabbitmq.server.port | default .Values.rabbitmq.server.port }}
    targetPort: {{ .Values.global.rabbitmq.server.port | default .Values.rabbitmq.server.port }}
  selector:
    app: rabbitmq
  type: ClusterIP
