apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-contactservice-svc
  labels:
    sfdcdemo: contactservice-svc
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "contactservice-port-9002"
    port: {{ .Values.global.contactservice.port | default .Values.contactservice.port }}
    targetPort: {{ .Values.global.contactservice.port | default .Values.contactservice.port }}
    nodePort: {{ .Values.contactservice.nodePort }}
  selector:
    app: {{ .Release.Name }}-contactservice
  type: NodePort
