apiVersion: v1
kind: Service
metadata:
  name: contactservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-contactservice"
    port: {{ .Values.global.contactservice.port | default .Values.contactservice.port }}
    targetPort: {{ .Values.global.contactservice.port | default .Values.contactservice.port }}
  selector:
    app: contactservice
  type: ClusterIP
