apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: contactservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - contactservice.{{ .Values.global.domain }}
  - contactservice.sfdcdemo.svc.cluster.local
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: contactservice
        subset: v2