version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  configserver:
    image: jigsheth57/configserver:latest
    container_name: configserver
    environment:
      - PORT=8888
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/jigsheth57/config-repo
    ports:
      - "8888:8888"

  discovery:
    image: jigsheth57/eurekaserver:latest
    container_name: discovery
    environment:
      - PORT=8761
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8761:8761"

  hystrixdashboard:
    image: jigsheth57/hystrixdashboard:latest
    container_name: hystrixdashboard
    environment:
      - PORT=7979
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "7979:7979"
    depends_on:
      rabbitmq:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      turbine:
        condition: service_started

  authservice:
    image: jigsheth57/authservice:latest
    environment:
      - PORT=9000
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "9000:9000"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy

  accountservice:
    image: jigsheth57/accountservice:latest
    environment:
      - PORT=9001
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
    - "9001:9001"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      authservice:
        condition: service_healthy

  contactservice:
    image: jigsheth57/contactservice:latest
    environment:
      - PORT=9002
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "9002:9002"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      authservice:
        condition: service_healthy
      accountservice:
        condition: service_healthy

  opportunityservice:
    image: jigsheth57/opportunityservice:latest
    environment:
      - PORT=9003
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "9003:9003"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      authservice:
        condition: service_healthy
      accountservice:
        condition: service_healthy
      contactservice:
        condition: service_healthy

  gatewayservice:
    image: jigsheth57/gatewayservice:latest
    environment:
      - PORT=9012
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "9012:9012"
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      authservice:
        condition: service_healthy
      accountservice:
        condition: service_healthy
      contactservice:
        condition: service_healthy
      opportunityservice:
        condition: service_healthy

  turbine:
    image: jigsheth57/turbine:latest
    container_name: turbine
    environment:
      - PORT=8000
      - TURBINE_STREAMS=http://accountservice:9001/manage/hystrix.stream http://contactservice:9002/manage/hystrix.stream http://opportunityservice:9003/manage/hystrix.stream http://gatewayservice:9012/manage/hystrix.stream
    ports:
      - "8000:8000"
    depends_on:
      gatewayservice:
        condition: service_healthy
      accountservice:
        condition: service_healthy
      contactservice:
        condition: service_healthy
      opportunityservice:
        condition: service_healthy

  sfdcwebapp:
    image: jigsheth57/sfdcwebapp:latest
    environment:
      - PORT=9090
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "9090:9090"
    depends_on:
      rabbitmq:
        condition: service_started
      configserver:
        condition: service_healthy
      discovery:
        condition: service_healthy
      gatewayservice:
        condition: service_healthy

  # mysql:
  #   image: openzipkin/zipkin-mysql
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #
  # zipkin:
  #   image: openzipkin/zipkin
  #   container_name: zipkin
  #   environment:
  #     - STORAGE_TYPE=mysql
  #     - MYSQL_HOST=mysql
  #     - RABBIT_ADDRESSES=rabbitmq
  #     - RABBIT_USER=guest
  #     - RABBIT_PASSWORD=guest
  #   ports:
  #     - "9411:9411"
  #   depends_on:
  #     rabbitmq:
  #       condition: service_started
  #     mysql:
  #       condition: service_started
