apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-portal-svc
  labels:
    sfdcdemo: portal-svc
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "portal-port-9090"
    port: {{ .Values.global.portal.port | default .Values.portal.port }}
    targetPort: {{ .Values.global.portal.port | default .Values.portal.port }}
  selector:
    app: {{ .Release.Name }}-portal
  type: ClusterIP
