server:
  port: ${PORT:8761}

management:
  endpoints:
    web:
      base-path: /manage

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO

---
spring:
  profiles: local
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
---
spring:
  profiles: cloud
