apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  labels:
    app: discovery
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: discovery
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: discovery
          image: {{ .Values.global.registry }}{{ .Values.global.discovery.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- include "discovery.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.discovery.port | default .Values.discovery.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: discovery
          ports:
          - containerPort: {{ .Values.global.discovery.port | default .Values.discovery.port }}
