apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: discovery
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - discovery.{{ .Values.global.domain }}
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: discovery
        port:
          number: {{ .Values.global.discovery.port | default .Values.discovery.port }}