apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: {{ .Release.Name }}-ingress-controller
    {{- include "sfdcapps.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName:  {{ .Release.Name }}-ingress-controller
    servicePort: 80
  rules:
  - host: authservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-authservice-svc
          servicePort: {{ .Values.global.authservice.port }}
  - host: accountservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-accountservice-svc
          servicePort: {{ .Values.global.accountservice.port }}
  - host: contactservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-contactservice-svc
          servicePort:  {{ .Values.global.contactservice.port }}
  - host: opportunityservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-opportunityservice-svc
          servicePort: {{ .Values.global.opportunityservice.port }}
  - host: gatewayservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-gatewayservice-svc
          servicePort: {{ .Values.global.gatewayservice.port }}
  - host: portal.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-portal-svc
          servicePort: {{ .Values.global.portal.port }}
  - host: hystrixdashboard.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-hystrixdashboard-svc
          servicePort: {{ .Values.global.hystrixdashboard.port }}
  - host: discovery.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-discovery-svc
          servicePort: {{ .Values.global.discovery.port }}
  - host: configserver.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-configserver-svc
          servicePort: {{ .Values.global.configserver.port }}
  - host: rabbitmq.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-rabbitmq-svc
          servicePort: {{ .Values.global.rabbitmq.management.port }}
