apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: {{ .Release.Name }}-ingress-controller
    {{- include "sfdcapps.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName:  {{ .Release.Name }}-ingress-controller
    servicePort: 80
  rules:
  - host: authservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-authservice-svc
          servicePort: 9000
  - host: accountservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-accountservice-svc
          servicePort: 9001
  - host: contactservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-contactservice-svc
          servicePort: 9002
  - host: opportunityservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-opportunityservice-svc
          servicePort: 9003
  - host: gatewayservice.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-gatewayservice-svc
          servicePort: 9012
  - host: portal.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-portalservice-svc
          servicePort: 9090
  - host: hystrixdashboard.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-hystrixdashboard-svc
          servicePort: 7979
  - host: discovery.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-discovery-svc
          servicePort: 8761
  - host: configserver.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-configserver-svc
          servicePort: 8888
