apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-configserver"
    port: {{ .Values.global.configserver.port | default .Values.configserver.port }}
    targetPort: {{ .Values.global.configserver.port | default .Values.configserver.port }}
  selector:
    app: configserver
  type: ClusterIP
