apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portal
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - portal.{{ .Values.global.domain }}
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: portal
        port:
          number: {{ .Values.global.portal.port | default .Values.portal.port }}