apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gatewayservice-svc
  labels:
    sfdcdemo: gatewayservice-svc
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "gatewayservice-port-9012"
    port: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port }}
    targetPort: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port }}
    nodePort: {{ .Values.gatewayservice.nodePort }}
  selector:
    app: {{ .Release.Name }}-gatewayservice
  type: NodePort
