apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-discovery"
    port: {{ .Values.global.discovery.port | default .Values.discovery.port }}
    targetPort: {{ .Values.global.discovery.port | default .Values.discovery.port }}
  selector:
    app: discovery
  type: ClusterIP
