apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
    app: accountservice
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: accountservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: accountservice
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: accountservice
          image: {{ .Values.global.registry }}{{ .Values.global.accountservice.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "1Gi"
              cpu: 500m
          {{- include "accountservice.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.accountservice.port | default .Values.accountservice.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: accountservice
          ports:
          - containerPort: {{ .Values.global.accountservice.port | default .Values.accountservice.port }}
