apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  labels:
    app: configserver
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: configserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configserver
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: configserver
          image: {{ .Values.global.registry }}{{ .Values.global.configserver.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "750Mi"
              cpu: 250m
          {{- include "configserver.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.configserver.port | default .Values.configserver.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: configserver
          ports:
          - containerPort: {{ .Values.global.configserver.port | default .Values.configserver.port }}
