apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-configserver-svc
  labels:
    sfdcdemo: configserver-svc
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "configserver-port-8888"
    port: {{ .Values.global.configserver.port | default .Values.configserver.port }}
    targetPort: {{ .Values.global.configserver.port | default .Values.configserver.port }}
  selector:
    app: {{ .Release.Name }}-configserver
  type: ClusterIP
