apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: configserver
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - configserver.{{ .Values.global.domain }}
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: configserver
        subset: v2