apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  labels:
    app: gatewayservice
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gatewayservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gatewayservice
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: gatewayservice
          image: {{ .Values.global.registry }}{{ .Values.global.gatewayservice.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- include "gatewayservice.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: gatewayservice
          ports:
          - containerPort: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port }}
