apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-gatewayservice"
    port: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port }}
    targetPort: {{ .Values.global.gatewayservice.port | default .Values.gatewayservice.port }}
  selector:
    app: gatewayservice
  type: ClusterIP
