apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: portal
          image: {{ .Values.global.registry }}{{ .Values.global.portal.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "750Mi"
              cpu: 500m
          {{- include "portal.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: configmap
          env:
          - name: PORT
            value: {{ .Values.global.portal.port | default .Values.portal.port | quote }}
          - name: WAVEFRONT_APPLICATION_SERVICE
            value: portal
          ports:
          - containerPort: {{ .Values.global.portal.port | default .Values.portal.port }}
