apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-portal"
    port: {{ .Values.global.portal.port | default .Values.portal.port }}
    targetPort: {{ .Values.global.portal.port | default .Values.portal.port }}
  selector:
    app: portal
  type: ClusterIP
