apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-contactservice
  labels:
    app: {{ .Release.Name }}-contactservice
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-contactservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-contactservice
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-contactservice
          image: {{ .Values.global.registry }}{{ .Values.global.contactservice.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- include "contactservice.healthProbes" . | indent 10 }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          env:
          - name: PORT
            value: {{ .Values.global.contactservice.port | default .Values.contactservice.port | quote }}
          ports:
          - containerPort: {{ .Values.global.contactservice.port | default .Values.contactservice.port }}
