apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: opportunityservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  host: opportunityservice
  subsets:
    - name: v2
      labels:
        version: v2
