apiVersion: v1
kind: Service
metadata:
  name: opportunityservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-opportunityservice"
    port: {{ .Values.global.opportunityservice.port | default .Values.opportunityservice.port }}
    targetPort: {{ .Values.global.opportunityservice.port | default .Values.opportunityservice.port }}
  selector:
    app: opportunityservice
  type: ClusterIP
