apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: opportunityservice
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  hosts:
  - opportunityservice.{{ .Values.global.domain }}
  - opportunityservice.sfdcdemo.svc.cluster.local
  gateways:
  - gateway
  http:
  - route:
    - destination:
        host: opportunityservice
        subset: v2