apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    sfdcdemo: sfdc-configmap
    {{- include "sfdcapps.labels" . | indent 4 }}
data:
  SPRING_CLOUD_CONFIG_URI: http://{{ .Release.Name }}-configserver-svc:{{ .Values.global.configserver.port }}
  SFDC_AUTHSERVICE_ENDPOINT: http://{{ .Release.Name }}-authservice-svc:{{ .Values.global.authservice.port }}
  REDIS_HOST: {{ .Release.Name }}-redis-svc
  SPRING_REDIS_HOST: {{ .Release.Name }}-redis-svc
  RABBITMQ_HOST: {{ .Release.Name }}-rabbitmq-svc
  SPRING_RABBITMQ_HOST: {{ .Release.Name }}-rabbitmq-svc
  EUREKA_HOST: {{ .Release.Name }}-discovery-svc
  {{- with .Values.spring }}
  SPRING_PROFILES_ACTIVE: {{ .profiles.active }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: {{ .cloud.config.server.git.uri }}
  {{- end }}
  {{- with .Values.spring.rabbitmq }}
  SPRING_RABBITMQ_PORT: {{ .port | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .username }}
  SPRING_RABBITMQ_PASSWORD: {{ .password }}
  {{- end }}
