apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.global.registry }}{{ .Values.global.redis.image.repository | default .Values.image.repository }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          resources:
            limits:
              memory: "1Gi"
              cpu: 500m
          {{- include "redis.healthProbes" . | indent 10 }}
          ports:
          - containerPort: {{ .Values.global.redis.port | default .Values.redis.port }}
