apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        {{- include "sfdcapps.labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}-redis
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.global.redis.port | default .Values.redis.port }}
          {{- include "redis.healthProbes" . | indent 10 }}
