apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-svc
  labels:
    sfdcdemo: redis-svc
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "redis-port-6379"
    port: {{ .Values.global.redis.port | default .Values.redis.port }}
    targetPort: {{ .Values.global.redis.port | default .Values.redis.port }}
  selector:
    app: {{ .Release.Name }}-redis
  type: ClusterIP
