apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
spec:
  ports:
  - name: "tcp-redis"
    port: {{ .Values.global.redis.port | default .Values.redis.port }}
    targetPort: {{ .Values.global.redis.port | default .Values.redis.port }}
  selector:
    app: redis
  type: ClusterIP
