# Default values for sfdcapps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

spring:
  profiles:
    active: local
  rabbitmq:
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jigsheth57/config-repo.git

global:
  registry: jigsheth57/
  redis:
    image:
      repository: redis:alpine
    port: 6379
  rabbitmq:
    image:
      repository: rabbitmq:3-management
    management:
      port: 15672
    server:
      port: 5672
  configserver:
    image:
      repository: configserver:2.3.1
    port: 8888
  authservice:
    image:
      repository: authservice:2.3.1
    port: 8080 # default 9000
  accountservice:
    image:
      repository: accountservice:2.3.1
    port: 8080 # default 9001
  contactservice:
    image:
      repository: contactservice:2.3.1
    port: 8080 # default 9002
  opportunityservice:
    image:
      repository: opportunityservice:2.3.1
    port: 8080 # default 9003
  portal:
    image:
      repository: sfdcwebapp:2.3.1
    port: 8080 # default 9090
  image:
    pullPolicy: IfNotPresent # IfNotPresent
  domain: tkg.local.tanzuapps.org
