apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  labels:
    {{- include "sfdcapps.labels" . | indent 4 }}
data:
  SPRING_CLOUD_CONFIG_URI: http://configserver:{{ .Values.global.configserver.port }}
  SFDC_AUTHSERVICE_ENDPOINT: http://authservice:{{ .Values.global.authservice.port }}
  SFDC_ACCOUNTSERVICE_ENDPOINT: http://accountservice:{{ .Values.global.accountservice.port }}
  SFDC_CONTACTSERVICE_ENDPOINT: http://contactservice:{{ .Values.global.contactservice.port }}
  SFDC_OPPORTUNITYSERVICE_ENDPOINT: http://opportunityservice:{{ .Values.global.opportunityservice.port }}
  REDIS_HOST: redis
  SPRING_REDIS_HOST: redis
  RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_HOST: rabbitmq
  EUREKA_HOST: discovery
  WAVEFRONT_APPLICATION_NAME: sfdcdemo
  {{- with .Values.spring }}
  SPRING_PROFILES_ACTIVE: {{ .profiles.active }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: {{ .cloud.config.server.git.uri }}
  {{- end }}
  {{- with .Values.spring.rabbitmq }}
  SPRING_RABBITMQ_PORT: {{ .port | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .username }}
  SPRING_RABBITMQ_PASSWORD: {{ .password }}
  {{- end }}
