apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: sfdcdemo
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: sfdcdemo
spec:
  host: "*.sfdcdemo.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL