# Default values for rabbitmqchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent

redis:
  port: 6379
  nodePort: 30379
